defmodule PhoenixExRatatui.LiveViewTest do
  @moduledoc """
  End-to-end tests for the `PhoenixExRatatui.LiveView` macro and its
  generated callbacks.

  Uses `Phoenix.LiveViewTest.live_isolated/3` so we don't have to wire
  up a router. The `TestEndpoint` started in `test_helper.exs` handles
  the LV machinery; `PhoenixExRatatui.TestLive` is a unified-module
  fixture that `use`s the macro and defines its own `tui_*` callbacks
  (the macro's `@after_compile` hook generates the matching
  `PhoenixExRatatui.TestLive.Runtime` proxy).

  We can't drive a real browser hook from here, so we simulate the
  hook's events with `render_hook/3` and assert on the server-side
  responses with `assert_push_event/3`.
  """

  use ExUnit.Case, async: true

  import Phoenix.ConnTest
  import Phoenix.LiveViewTest

  alias ExRatatui.CellSession
  alias PhoenixExRatatui.FailingTestLive
  alias PhoenixExRatatui.LiveView, as: PXRLV
  alias PhoenixExRatatui.TestLive

  doctest PhoenixExRatatui.LiveView

  @endpoint PhoenixExRatatui.TestEndpoint

  describe "__build_using_quote__/1 (compile-time helper)" do
    # The __using__ macro delegates to __build_using_quote__/1 so the
    # option-parsing path is runtime-callable (and therefore tracked
    # by mix test --cover, which doesn't see compile-time macro
    # expansion). These tests assert option-handling shape directly.

    test "accepts no options and returns a quoted AST" do
      ast = PXRLV.__build_using_quote__([])
      assert is_tuple(ast)
      assert elem(ast, 0) == :__block__
    end

    test "applies the configured :container_id default" do
      ast = PXRLV.__build_using_quote__([])
      ast_string = Macro.to_string(ast)
      assert ast_string =~ "phoenix-ex-ratatui"
    end

    test "accepts a custom :container_id" do
      ast = PXRLV.__build_using_quote__(container_id: "my-custom-tui")
      ast_string = Macro.to_string(ast)
      assert ast_string =~ "my-custom-tui"
    end

    test "__using__ macro body is invoked when expanded at runtime" do
      # The defmacro __using__ body delegates to __build_using_quote__/1.
      # That delegation line runs at compile time, which `mix test
      # --cover` doesn't track (cover instrumentation kicks in after
      # lib/ has compiled). Invoking the macro from inside a runtime
      # test via Code.eval_string makes the macro body run while cover
      # IS active, so the delegation line gets tracked. Without this
      # test, that single line shows up as uncovered.
      module_name = String.to_atom("Elixir.PhoenixExRatatui.LiveViewTest.RuntimeMacroTest")

      Code.eval_string("""
      defmodule #{inspect(module_name)} do
        use PhoenixExRatatui.LiveView
      end
      """)

      assert Code.ensure_loaded?(module_name)
      # The macro's @after_compile hook should have created a sibling
      # Runtime proxy — verify it exists and conforms to ExRatatui.App.
      runtime = Module.concat(module_name, "Runtime")
      assert Code.ensure_loaded?(runtime)
      assert function_exported?(runtime, :mount, 1)
      assert function_exported?(runtime, :render, 2)
      assert function_exported?(runtime, :handle_event, 2)

      :code.purge(runtime)
      :code.delete(runtime)
      :code.purge(module_name)
      :code.delete(module_name)
    end
  end

  describe "__define_runtime__/2 (proxy generation, callbacks runtime)" do
    test "generates a Runtime sibling that delegates to the user module's tui_* callbacks" do
      # TestLive.Runtime is generated by the macro's @after_compile
      # hook. Calling its callbacks should reach TestLive's tui_*
      # implementations via the proxy delegation.
      assert TestLive.Runtime.mount([]) == {:ok, %{n: 0}}

      frame = %ExRatatui.Frame{width: 10, height: 1}
      assert [{_widget, _rect}] = TestLive.Runtime.render(%{n: 0}, frame)

      assert TestLive.Runtime.handle_event(%ExRatatui.Event.Key{code: "x"}, %{n: 0}) ==
               {:noreply, %{n: 1}}

      assert TestLive.Runtime.handle_event(%ExRatatui.Event.Key{code: "q"}, %{n: 0}) ==
               {:stop, %{n: 0}}
    end

    test "default tui_handle_info/2 returns {:noreply, state} via the proxy" do
      assert TestLive.Runtime.handle_info(:anything, %{n: 7}) == {:noreply, %{n: 7}}
    end

    test "default tui_terminate/2 returns :ok via the proxy" do
      assert TestLive.Runtime.terminate(:normal, %{n: 0}) == :ok
    end
  end

  describe "__define_runtime__/2 (proxy generation, reducer runtime)" do
    alias PhoenixExRatatui.ReducerTestLive

    test "generates a reducer-runtime Runtime sibling" do
      # The reducer proxy uses `ExRatatui.App, runtime: :reducer`.
      # __runtime__/0 is set to :reducer by that `use`, so we can
      # confirm the right branch fired by reading it.
      assert ReducerTestLive.Runtime.__runtime__() == :reducer

      # The reducer runtime exposes init/1 (not mount/1) plus update/2
      # wrapping `{:event, _}` and `{:info, _}` messages.
      assert function_exported?(ReducerTestLive.Runtime, :init, 1)
      assert function_exported?(ReducerTestLive.Runtime, :update, 2)
      assert function_exported?(ReducerTestLive.Runtime, :subscriptions, 1)
    end

    test "init/1 delegates to tui_init/1" do
      assert ReducerTestLive.Runtime.init([]) == {:ok, %{n: 0}}
    end

    test "update/2 delegates to tui_update/2 with wrapped messages" do
      assert ReducerTestLive.Runtime.update({:event, %ExRatatui.Event.Key{code: "x"}}, %{n: 0}) ==
               {:noreply, %{n: 1}}

      assert ReducerTestLive.Runtime.update({:event, %ExRatatui.Event.Key{code: "q"}}, %{n: 5}) ==
               {:stop, %{n: 5}}

      assert ReducerTestLive.Runtime.update({:info, :tick}, %{n: 0}) == {:noreply, %{n: 0}}
    end

    test "default tui_subscriptions/1 returns []" do
      assert ReducerTestLive.Runtime.subscriptions(%{n: 0}) == []
    end
  end

  describe "__build_using_quote__/1 with :runtime option" do
    test "rejects unknown runtime values" do
      assert_raise ArgumentError, ~r":runtime must be :callbacks or :reducer", fn ->
        PXRLV.__build_using_quote__(runtime: :nonsense)
      end
    end

    test "callbacks runtime is the default when :runtime is not given" do
      ast_string = PXRLV.__build_using_quote__([]) |> Macro.to_string()
      # The tui_mount/1 default appears for the callbacks runtime; the
      # reducer runtime would have tui_init/1 instead. Match on `(_opts)`
      # to disambiguate `tui_mount` from `tui_mount_opts`.
      assert ast_string =~ "tui_mount(_opts)"
      refute ast_string =~ "tui_init(_opts)"
    end

    test "reducer runtime injects tui_init / tui_update / tui_subscriptions defaults" do
      ast_string = PXRLV.__build_using_quote__(runtime: :reducer) |> Macro.to_string()
      assert ast_string =~ "tui_init(_opts)"
      assert ast_string =~ "tui_update"
      assert ast_string =~ "tui_subscriptions"
      refute ast_string =~ "tui_mount(_opts)"
      refute ast_string =~ "tui_handle_event"
    end
  end

  describe "__handle_server_exit__/2 (compile-time helper)" do
    # Direct unit tests for the EXIT handler. The integration test
    # below ("App returning :stop ends the session...") covers the
    # matching path end-to-end via the macro; this block locks the
    # fall-through behaviour where an EXIT arrives from a process
    # that ISN'T our runtime server (e.g. a user-spawned Task that
    # crashed in their own mount/3 override).
    alias Phoenix.LiveView.Socket

    test "matching server pid clears :tui and flips :tui_ended" do
      fake_server = self()

      socket = %Socket{
        endpoint: PhoenixExRatatui.TestEndpoint,
        assigns: %{
          __changed__: %{},
          tui: %{server: fake_server, cell_session: :ref, mod: TestLive.Runtime},
          tui_ended: false
        }
      }

      result = PXRLV.__handle_server_exit__(socket, fake_server)

      assert result.assigns.tui == nil
      assert result.assigns.tui_ended == true
    end

    test "non-matching pid leaves the socket unchanged" do
      our_server = self()
      stranger = spawn(fn -> :ok end)

      socket = %Socket{
        endpoint: PhoenixExRatatui.TestEndpoint,
        assigns: %{
          __changed__: %{},
          tui: %{server: our_server, cell_session: :ref, mod: TestLive.Runtime},
          tui_ended: false
        }
      }

      result = PXRLV.__handle_server_exit__(socket, stranger)

      # The user might have spawned their own Task that exited; we
      # ignore those signals instead of clobbering the live TUI's
      # state.
      assert result.assigns.tui != nil
      assert result.assigns.tui_ended == false
    end

    test "EXIT arriving while :tui is already nil is a no-op" do
      # If the runtime had already been torn down by the time the
      # EXIT message reaches the LV (e.g. handler order during a
      # disconnect), don't accidentally re-flip the ended state on
      # top of an already-cleared assigns.
      socket = %Socket{
        endpoint: PhoenixExRatatui.TestEndpoint,
        assigns: %{__changed__: %{}, tui: nil, tui_ended: false}
      }

      result = PXRLV.__handle_server_exit__(socket, self())

      assert result.assigns.tui == nil
      assert result.assigns.tui_ended == false
    end
  end

  describe "decode_input/1 (public helper)" do
    # The decoder is exposed for users hand-rolling their own LiveView
    # without the macro, so it gets its own focused tests beyond the
    # mount-flow integration coverage below.

    test "decodes a key event payload into %ExRatatui.Event.Key{}" do
      assert PXRLV.decode_input(%{
               "kind" => "key",
               "code" => "a",
               "modifiers" => [],
               "press_kind" => "press"
             }) == %ExRatatui.Event.Key{code: "a", modifiers: [], kind: "press"}
    end

    test "modifier strings convert to existing atoms only" do
      decoded =
        PXRLV.decode_input(%{
          "kind" => "key",
          "code" => "c",
          "modifiers" => ["ctrl", "shift"]
        })

      assert decoded.modifiers == [:ctrl, :shift]
    end

    test "press_kind defaults to \"press\" when omitted" do
      decoded = PXRLV.decode_input(%{"kind" => "key", "code" => "a", "modifiers" => []})
      assert decoded.kind == "press"
    end

    test "missing modifiers list defaults to empty" do
      decoded = PXRLV.decode_input(%{"kind" => "key", "code" => "a"})
      assert decoded.modifiers == []
    end
  end

  describe "mount" do
    test "renders the hook container with the runtime proxy module name" do
      {:ok, _view, html} = live_isolated(build_conn(), TestLive)

      assert html =~ ~s(id="phoenix-ex-ratatui")
      assert html =~ ~s(phx-hook="PhoenixExRatatuiHook")
      assert html =~ ~s(phx-update="ignore")
      # The macro inserts the runtime module name into a data-* attr
      # so the hook can read it client-side without a separate
      # round-trip. inspect/1 produces "PhoenixExRatatui.TestLive.Runtime".
      assert html =~ ~s(data-phx-ex-ratatui-runtime="PhoenixExRatatui.TestLive.Runtime")
    end

    test "no error message is rendered on a successful mount" do
      {:ok, _view, html} = live_isolated(build_conn(), TestLive)
      refute html =~ "TUI error:"
    end
  end

  describe "phx_ex_ratatui:resize event" do
    test "first resize starts the Transport and pushes the initial frame" do
      {:ok, view, _html} = live_isolated(build_conn(), TestLive)

      render_hook(view, "phx_ex_ratatui:resize", %{"cols" => 20, "rows" => 4})

      assert_push_event(view, "phx_ex_ratatui:render", payload, 1000)
      assert payload["width"] == 20
      assert payload["height"] == 4
      assert length(payload["ops"]) == 20 * 4

      [first_op | _] = payload["ops"]
      assert is_list(first_op) and length(first_op) == 7
    end

    test "the pushed ops carry the symbols the app actually painted" do
      # TestLive paints "n=0" at row 0 (see PhoenixExRatatui.TestApp).
      # This pins the full server -> wire contract: not just that a
      # frame fired, but that the rendered glyphs reach the client at
      # the right cells.
      {:ok, view, _html} = live_isolated(build_conn(), TestLive)

      render_hook(view, "phx_ex_ratatui:resize", %{"cols" => 20, "rows" => 4})
      assert_push_event(view, "phx_ex_ratatui:render", payload, 1000)

      # Each op is [row, col, sym, fg, bg, mods, skip]. Pull row 0's
      # first three cells and assert the painted text.
      row0 = for [0, col, sym | _] <- payload["ops"], col in 0..2, do: {col, sym}

      assert Enum.sort(row0) == [{0, "n"}, {1, "="}, {2, "0"}]
    end

    @tag capture_log: true
    test "Transport.start_link error from a mount-failing app surfaces as a :tui_error assign" do
      {:ok, view, _html} = live_isolated(build_conn(), FailingTestLive)

      render_hook(view, "phx_ex_ratatui:resize", %{"cols" => 10, "rows" => 2})

      html = render(view)
      assert html =~ "TUI error:"
      assert html =~ "mount_failed"

      refute_push_event_arrives(view, "phx_ex_ratatui:render", 100)
    end

    test "subsequent resize delegates to Transport.resize and pushes a full frame at the new size" do
      {:ok, view, _html} = live_isolated(build_conn(), TestLive)

      render_hook(view, "phx_ex_ratatui:resize", %{"cols" => 10, "rows" => 2})
      assert_push_event(view, "phx_ex_ratatui:render", first_payload, 1000)
      assert first_payload["width"] == 10

      render_hook(view, "phx_ex_ratatui:resize", %{"cols" => 20, "rows" => 5})
      assert_push_event(view, "phx_ex_ratatui:render", second_payload, 1000)
      assert second_payload["width"] == 20
      assert second_payload["height"] == 5
      assert length(second_payload["ops"]) == 20 * 5
    end

    @tag capture_log: true
    test "resize on a closed underlying CellSession assigns :tui_error" do
      {:ok, view, _html} = live_isolated(build_conn(), TestLive)

      render_hook(view, "phx_ex_ratatui:resize", %{"cols" => 10, "rows" => 2})
      assert_push_event(view, "phx_ex_ratatui:render", _, 1000)

      assigns = :sys.get_state(view.pid).socket.assigns
      :ok = CellSession.close(assigns.tui.cell_session)

      render_hook(view, "phx_ex_ratatui:resize", %{"cols" => 20, "rows" => 5})

      html = render(view)
      assert html =~ "TUI error:"
      assert html =~ "session closed"
    end
  end

  describe "phx_ex_ratatui:input event" do
    test "input before resize is silently dropped (no Transport yet)" do
      {:ok, view, _html} = live_isolated(build_conn(), TestLive)

      render_hook(view, "phx_ex_ratatui:input", %{
        "kind" => "key",
        "code" => "a",
        "modifiers" => []
      })

      refute_push_event_arrives(view, "phx_ex_ratatui:render", 100)
    end

    @tag capture_log: true
    test "App returning :stop ends the session and renders the refresh prompt" do
      {:ok, view, _html} = live_isolated(build_conn(), TestLive)

      render_hook(view, "phx_ex_ratatui:resize", %{"cols" => 8, "rows" => 1})
      assert_push_event(view, "phx_ex_ratatui:render", _, 1000)

      # `q` is the TestLive.tui_handle_event/2 :stop trigger.
      render_hook(view, "phx_ex_ratatui:input", %{
        "kind" => "key",
        "code" => "q",
        "modifiers" => []
      })

      assert_assigns_eventually(view, fn assigns ->
        assigns.tui == nil and assigns.tui_ended == true
      end)

      html = render(view)
      assert html =~ "tui session ended"
      assert html =~ "[refresh]"
    end

    test "input after resize forwards to the Transport and triggers a re-render" do
      {:ok, view, _html} = live_isolated(build_conn(), TestLive)

      render_hook(view, "phx_ex_ratatui:resize", %{"cols" => 10, "rows" => 1})
      assert_push_event(view, "phx_ex_ratatui:render", _initial, 1000)

      render_hook(view, "phx_ex_ratatui:input", %{
        "kind" => "key",
        "code" => "x",
        "modifiers" => []
      })

      assert_push_event(view, "phx_ex_ratatui:render", payload, 1000)
      assert payload["width"] == 10
      assert payload["height"] == 1
      assert match?([_ | _], payload["ops"])
    end
  end

  # ----------------------------------------------------------------------
  # Helpers
  # ----------------------------------------------------------------------

  defp assert_assigns_eventually(view, predicate, timeout_ms \\ 1000) do
    deadline = System.monotonic_time(:millisecond) + timeout_ms
    do_assert_assigns_eventually(view, predicate, deadline)
  end

  defp do_assert_assigns_eventually(view, predicate, deadline) do
    if predicate.(:sys.get_state(view.pid).socket.assigns) do
      :ok
    else
      if System.monotonic_time(:millisecond) > deadline do
        flunk(
          "assigns never matched predicate: #{inspect(:sys.get_state(view.pid).socket.assigns)}"
        )
      else
        Process.sleep(20)
        do_assert_assigns_eventually(view, predicate, deadline)
      end
    end
  end

  defp refute_push_event_arrives(view, event, timeout_ms) do
    refute_receive {:phoenix, :send_update, _}, timeout_ms
    refute_receive {%Phoenix.Socket.Reply{ref: _}, _}, 0

    assert_no_push_event(view, event)
  end

  defp assert_no_push_event(_view, _event) do
    receive do
      {:push_event, _ref, _payload} = msg ->
        flunk("unexpected push_event in mailbox: #{inspect(msg)}")
    after
      0 -> :ok
    end
  end
end
