defmodule PhoenixExRatatui.MixProject do
  use Mix.Project

  @description "Run ExRatatui apps inside Phoenix LiveView"
  @source_url "https://github.com/mcass19/phoenix_ex_ratatui"
  @changelog_url @source_url <> "/blob/main/CHANGELOG.md"
  @version "0.1.0"

  def project do
    [
      app: :phoenix_ex_ratatui,
      description: @description,
      version: @version,
      elixir: "~> 1.17",
      elixirc_paths: elixirc_paths(Mix.env()),
      start_permanent: Mix.env() == :prod,
      aliases: aliases(),
      deps: deps(),
      package: package(),
      name: "PhoenixExRatatui",
      homepage_url: @source_url,
      source_url: @source_url,
      docs: docs(),
      test_coverage: [
        summary: [threshold: 100],
        ignore_modules: [
          # Test fixtures — exercised by tests, not production surface.
          PhoenixExRatatui.TestApp,
          PhoenixExRatatui.FailingMountApp,
          PhoenixExRatatui.TestLive,
          PhoenixExRatatui.FailingTestLive,
          PhoenixExRatatui.TestParentLive,
          PhoenixExRatatui.TestRouter,
          # Phoenix.Router auto-generates a `<Router>.Helpers` module
          # for path/url helpers; nothing in the test suite calls
          # them, but they show up in cover with 0%. Ignore.
          PhoenixExRatatui.TestRouter.Helpers,
          PhoenixExRatatui.TestEndpoint,
          PhoenixExRatatui.TestErrorHTML,
          # Wrappers generated by the test router's `tui_live` calls.
          # Their content is just `use PhoenixExRatatui.LiveView, app: …`
          # — every behaviour path is exercised by the LiveView macro
          # tests against the equivalent hand-written `TestLive`. We
          # ignore them by name so cover doesn't double-count.
          Module.concat(
            PhoenixExRatatui.TestRouter,
            "TuiLive_#{:erlang.phash2({"/tui_test", PhoenixExRatatui.TestApp})}"
          ),
          Module.concat(
            PhoenixExRatatui.TestRouter,
            "TuiLive_#{:erlang.phash2({"/tui_admin", PhoenixExRatatui.TestApp})}"
          ),
          # `:cover` reports line 1 (the `defmodule` line) as missed
          # for any module that does `use Phoenix.LiveComponent`,
          # because the macro expansion injects helpers attributed
          # to that line that are never invoked by user code (they
          # exist for the LV runtime to call internally). Every
          # behaviour path in this module is covered by the
          # integration tests in `live_component_test.exs`; we
          # accept the cover-tooling quirk by excluding the module
          # from the overall threshold rather than chasing a
          # phantom miss.
          PhoenixExRatatui.LiveComponent
        ]
      ],
      dialyzer: [
        plt_local_path: "plts",
        plt_core_path: "plts/core"
      ]
    ]
  end

  def application do
    [
      extra_applications: [:logger]
    ]
  end

  defp elixirc_paths(:test), do: ["lib", "test/support"]
  defp elixirc_paths(_), do: ["lib"]

  defp aliases do
    [
      "assets.install": ["cmd --cd assets npm install"],
      "assets.build": ["cmd --cd assets npm run build"]
    ]
  end

  defp deps do
    [
      # Pinned to a path during pre-release while CellSession (the
      # primitive this package depends on) lives in ex_ratatui's
      # `[Unreleased]`. Swap to `{:ex_ratatui, "~> 0.9"}` once
      # ex_ratatui cuts the release that ships CellSession.
      {:ex_ratatui, path: "../ex_ratatui"},
      {:phoenix, "~> 1.7"},
      {:phoenix_live_view, "~> 1.1"},
      {:telemetry, "~> 1.0"},
      {:jason, "~> 1.4"},

      # Test
      {:lazy_html, "~> 0.1", only: :test},
      {:stream_data, "~> 1.1", only: :test},

      # Dev
      {:ex_doc, "~> 0.35", only: :dev, runtime: false},
      {:credo, "~> 1.7", only: :dev, runtime: false},
      {:dialyxir, "~> 1.4", only: :dev, runtime: false},

      # Path-deps fallback: ex_ratatui's NIF compile path needs rustler
      # available when no precompiled binary is found for the current
      # target. Required while we depend on ex_ratatui via `path:`. Once
      # ex_ratatui ships a release with CellSession and we flip to
      # `{:ex_ratatui, "~> 0.9"}`, this dep can drop — released versions
      # ship precompiled binaries for every supported target.
      {:rustler, ">= 0.0.0", only: [:dev, :test], runtime: false}
    ]
  end

  defp package do
    [
      licenses: ["MIT"],
      links: %{
        "GitHub" => @source_url,
        "Changelog" => @changelog_url
      },
      keywords: ~w(phoenix liveview tui terminal ratatui ex_ratatui),
      files: ~w(lib .formatter.exs mix.exs README.md LICENSE CHANGELOG.md)
    ]
  end

  defp docs do
    [
      main: "readme",
      source_ref: "v#{@version}",
      extras: [
        "README.md": [title: "Overview"],
        "guides/getting_started.md": [title: "Getting Started"],
        "CONTRIBUTING.md": [title: "Contributing"],
        "CHANGELOG.md": [title: "Changelog"]
      ],
      groups_for_modules: [
        Components: [
          PhoenixExRatatui,
          PhoenixExRatatui.LiveView,
          PhoenixExRatatui.LiveComponent
        ],
        Internals: [
          PhoenixExRatatui.Renderer.Html,
          PhoenixExRatatui.Telemetry,
          PhoenixExRatatui.Transport
        ]
      ]
    ]
  end
end
